// conversor-moedas-nuxt/pages/register.vue
<template>
    <div class="mx-auto md:max-w-2xl">
        <Card>
            <h2 class="text-center text-xl">Login</h2>

            <form @submit.prevent="login" method="post" action="/login">
                <div class="mt-5 space-y-5">
                    <div class="group-input">
                        <label for="name">Nome</label>
                        <input type="text" id="name" v-model="form.name" name="name" required />

                        <div v-if="errors.name" class="text-red-500 bg-red-200 mt-2 p-2 border border-red-500 rounded">
                            <span v-for="(message, index) in errors.name" :key="index">{{ message }}</span>
                        </div>
                    </div>

                    <div class="group-input">
                        <label for="email">E-mail</label>
                        <input type="email" id="email" v-model="form.email" name="email" required />

                        <div v-if="errors.email" class="text-red-500 bg-red-200 mt-2 p-2 border border-red-500 rounded">
                            <span v-for="(message, index) in errors.email" :key="index">{{ message }}</span>
                        </div>
                    </div>

                    <div class="group-input">
                        <label for="password">Senha</label>
                        <input type="password" id="password" v-model="form.password" name="password" required />

                        <div v-if="errors.password" class="text-red-500 bg-red-200 mt-2 p-2 border border-red-500 rounded">
                            <span v-for="(message, index) in errors.password" :key="index">{{ message }}</span>
                        </div>
                    </div>

                    <div class="group-input">
                        <label for="password_confirmation">Confirmar senha</label>
                        <input type="password" id="password_confirmation" v-model="form.password_confirmation" name="password_confirmation" required />

                        <div v-if="errors.password_confirmation" class="text-red-500 bg-red-200 mt-2 p-2 border border-red-500 rounded">
                            <span v-for="(message, index) in errors.password_confirmation" :key="index">{{ message }}</span>
                        </div>

                        <div v-if="form.password !== form.password_confirmation" class="text-red-500 bg-red-200 mt-2 p-2 border border-red-500 rounded">
                            <span>The password must be the same!</span>
                        </div>
                    </div>
                    <div class="flex items-center justify-end mt-5">
                        <Button class="mt-5" type="submit" :disabled="!registerBusy">Registrar-se</Button>
                    </div>
                </div>
            </form>

        </Card>
    </div>
</template>

<script lang="ts">
import Vue from 'vue'
import Card from '~/components/Card.vue'
import Button from '~/components/Button.vue'

export default Vue.extend({
    middleware: 'auth',
    auth: 'guest',
    components: { Card, Button },
    data() {
        return {
            form: {
                name: '',
                email: '',
                password: '',
                password_confirmation: ''
            },
            errors: {}
        };
    },
    methods: {
        async login() {
            await this.$axios.$post('/laravel/register', this.form)
                .then(res => this.$auth.loginWith('laravelSanctum', { data: this.form }))
        },
        registerBusy(): Boolean {
            return this.$auth.busy
        }
    }
})
</script>

<style scoped>
.group-input { @apply flex flex-col space-y-1; }
input { @apply rounded; }
</style>

// resources/js/Pages/Auth/Register.jsx
import { useEffect } from 'react';
import GuestLayout from '@/Layouts/GuestLayout';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import { Head, Link, useForm } from '@inertiajs/react';

export default function Register() {
    const { data, setData, post, processing, errors, reset } = useForm({
        name: '',
        email: '',
        password: '',
        password_confirmation: '',
    });

    useEffect(() => {
        return () => {
            reset('password', 'password_confirmation');
        };
    }, []);

    const submit = (e) => {
        e.preventDefault();

        post(route('register'));
    };

    return (
        <GuestLayout>
            <Head title="Registrar-se" />

            <form onSubmit={submit}>
                <div>
                    <InputLabel htmlFor="name" value="Nome" />

                    <TextInput
                        id="name"
                        name="name"
                        value={data.name}
                        className="mt-1 block w-full"
                        autoComplete="name"
                        isFocused={true}
                        onChange={(e) => setData('name', e.target.value)}
                        required
                    />

                    <InputError message={errors.name} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="email" value="Email" />

                    <TextInput
                        id="email"
                        type="email"
                        name="email"
                        value={data.email}
                        className="mt-1 block w-full"
                        autoComplete="username"
                        onChange={(e) => setData('email', e.target.value)}
                        required
                    />

                    <InputError message={errors.email} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="password" value="Senha" />

                    <TextInput
                        id="password"
                        type="password"
                        name="password"
                        value={data.password}
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                        onChange={(e) => setData('password', e.target.value)}
                        required
                    />

                    <InputError message={errors.password} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="password_confirmation" value="Confirmar Senha" />

                    <TextInput
                        id="password_confirmation"
                        type="password"
                        name="password_confirmation"
                        value={data.password_confirmation}
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                        onChange={(e) => setData('password_confirmation', e.target.value)}
                        required
                    />

                    <InputError message={errors.password_confirmation} className="mt-2" />
                </div>

                <div className="flex items-center justify-end mt-4">
                    <Link
                        href={route('login')}
                        className="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        Já é registrado?
                    </Link>

                    <PrimaryButton className="ms-4" disabled={processing}>
                        Registrar-se
                    </PrimaryButton>
                </div>
            </form>
        </GuestLayout>
    );
}
